name: "IaC Pipeline — Destroy"

on:
  workflow_dispatch:

env:
  TF_VERSION: "1.7.0"
  AWS_REGION: "us-east-1"

jobs:
  terraform-destroy:
    name: "Terraform — Destroy"
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: ${{ env.TF_VERSION }}

      - name: Terraform Init
        working-directory: terraform/
        run: terraform init

      - name: Terraform Destroy
        working-directory: terraform/
        env:
          TF_VAR_mongo_admin_password: ${{ secrets.MONGO_ADMIN_PASSWORD }}
          TF_VAR_mongo_app_password:   ${{ secrets.MONGO_APP_PASSWORD }}
        run: terraform destroy -auto-approve
